// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaakzgwwmmnmzochvult.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYWt6Z3d3bW1ubXpvY2h2dWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzc1NzYsImV4cCI6MjA3MjM1MzU3Nn0.FfBrpovY3ZQFCVrC0Qbv-hQc0B_TryWHNK7nZ6eo-iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});